import { useEffect, useState } from 'react';
import { useContentBuilder } from '@/contexts/ContentBuilderContext';
import { toast } from 'sonner';

/**
 * Custom hook to automatically generate meta information and solution analysis
 * when user lands on the Optimize & Review step
 */
export const useAutoGenerateMetaAndAnalysis = (
  generateMeta: () => Promise<void>,
  analyzeSolutionUsage: () => Promise<void>
) => {
  const { state } = useContentBuilder();
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [isAutoGenerating, setIsAutoGenerating] = useState(false);
  
  useEffect(() => {
    const autoGenerateRequired = async () => {
      // Only run once per session
      if (hasAutoGenerated || isAutoGenerating) return;
      
      // Check if content exists
      if (!state.content) return;
      
      const needsMetaGeneration = !state.metaTitle || !state.metaDescription;
      const needsSolutionAnalysis = state.selectedSolution && !state.solutionIntegrationMetrics;
      
      // If nothing needs to be generated, exit
      if (!needsMetaGeneration && !needsSolutionAnalysis) {
        setHasAutoGenerated(true);
        return;
      }
      
      try {
        setIsAutoGenerating(true);
        console.log('[useAutoGenerateMetaAndAnalysis] Starting auto-generation');
        
        const tasks = [];
        
        // Generate meta information if missing
        if (needsMetaGeneration) {
          console.log('[useAutoGenerateMetaAndAnalysis] Auto-generating meta information');
          tasks.push(generateMeta());
        }
        
        // Analyze solution integration if missing
        if (needsSolutionAnalysis) {
          console.log('[useAutoGenerateMetaAndAnalysis] Auto-analyzing solution integration');
          tasks.push(analyzeSolutionUsage());
        }
        
        // Run all tasks in parallel
        await Promise.all(tasks);
        
        console.log('[useAutoGenerateMetaAndAnalysis] Auto-generation completed');
        toast.success('Content analysis completed', {
          description: 'Meta information and solution integration analyzed',
          duration: 3000
        });
        
        setHasAutoGenerated(true);
      } catch (error) {
        console.error('[useAutoGenerateMetaAndAnalysis] Error during auto-generation:', error);
        // Don't show error toast, as individual functions already handle errors
      } finally {
        setIsAutoGenerating(false);
      }
    };
    
    autoGenerateRequired();
  }, [
    state.content, 
    state.metaTitle, 
    state.metaDescription,
    state.selectedSolution,
    state.solutionIntegrationMetrics,
    hasAutoGenerated,
    isAutoGenerating,
    generateMeta,
    analyzeSolutionUsage
  ]);
  
  return {
    isAutoGenerating,
    hasAutoGenerated
  };
};
