
import { ContentBuilderState } from './types';

export const initialState: ContentBuilderState = {
  activeStep: 0,
  steps: [
    {
      id: 0,
      name: 'Keywords',
      description: 'Select target keywords for your content',
      completed: false,
    },
    {
      id: 1,
      name: 'Content Type',
      description: 'Choose the type of content you want to create',
      completed: false,
    },
    {
      id: 2,
      name: 'SERP Analysis',
      description: 'Analyze search results for your keywords',
      completed: false,
    },
    {
      id: 3,
      name: 'Outline',
      description: 'Create an outline for your content',
      completed: false,
    },
    {
      id: 4,
      name: 'Write',
      description: 'Write your content using AI assistance',
      completed: false,
    },
    {
      id: 5,
      name: 'Optimize',
      description: 'Optimize your content for search engines',
      completed: false,
    },
    {
      id: 6,
      name: 'Publish',
      description: 'Publish or schedule your content',
      completed: false,
    },
  ],
  primaryKeyword: '',
  secondaryKeywords: [],
  keywordClusters: {},
  contentType: 'article',
  contentFormat: 'blog',
  contentTitle: '',
  outlineSections: [],
  serpAnalysisResults: null,
  serpKeywordsSelected: [],
  serpQuestionsSelected: [],
  isAnalyzing: false,
  isSaving: false,
  isPublishing: false,
  content: '',
  mainKeyword: '',
  selectedKeywords: [],
  selectedCluster: null,
  selectedSolution: null,
  serpData: null,
  serpSelections: [],
  outline: [],
  seoScore: 0,
  additionalInstructions: '',
};
