/**
 * Cross-Module Orchestration Tools
 * Chain reads and writes across modules atomically
 */

export const CROSS_MODULE_TOOL_DEFINITIONS = [
  {
    type: "function",
    function: {
      name: "promote_content_to_campaign",
      description: "Take an existing content item and create a new campaign around it. Use when user says 'turn this content into a campaign', 'promote article', or 'create campaign from content'.",
      parameters: {
        type: "object",
        properties: {
          content_id: { type: "string", description: "UUID of the content item to promote" },
          campaign_name: { type: "string", description: "Name for the new campaign" },
          objective: { type: "string", description: "Campaign objective" }
        },
        required: ["content_id"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "content_to_email",
      description: "Take content from the repository and create an email campaign from it. Use when user says 'email this content', 'send article as email', or 'create email from content'.",
      parameters: {
        type: "object",
        properties: {
          content_id: { type: "string", description: "UUID of the content item" },
          segment_id: { type: "string", description: "Target segment for the email" },
          subject: { type: "string", description: "Custom email subject (auto-generated from title if empty)" },
          from_name: { type: "string", description: "Sender name" }
        },
        required: ["content_id"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "campaign_content_to_engage",
      description: "Find content from a campaign and create an Engage email campaign from it. Use when user says 'email campaign content to contacts', 'send campaign results to audience'.",
      parameters: {
        type: "object",
        properties: {
          campaign_id: { type: "string", description: "UUID of the content campaign" },
          segment_id: { type: "string", description: "Target segment for the email" },
          subject: { type: "string", description: "Custom email subject" }
        },
        required: ["campaign_id"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "repurpose_for_social",
      description: "Take content and generate social media posts for specified platforms. Use when user says 'repurpose for social', 'create social posts from article', or 'share content on social media'.",
      parameters: {
        type: "object",
        properties: {
          content_id: { type: "string", description: "UUID of the content item to repurpose" },
          platforms: { type: "array", items: { type: "string", enum: ["twitter", "linkedin", "facebook", "instagram"] }, description: "Target social platforms" }
        },
        required: ["content_id", "platforms"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "publish_to_website",
      description: "Publish a content item to the user's connected WordPress or Wix site. Use when user says 'publish to my website', 'push to WordPress', 'post this on my blog', 'publish this article to my site'.",
      parameters: {
        type: "object",
        properties: {
          content_id: { type: "string", description: "UUID of the content item to publish" },
          status: { type: "string", enum: ["draft", "publish"], description: "WordPress post status. Default: publish" },
          scheduled_at: { type: "string", description: "ISO datetime for scheduled publishing (optional)" }
        },
        required: ["content_id"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "create_campaign",
      description: "Create a new content campaign from scratch. Use when user says 'create a campaign', 'new campaign', 'start a campaign about [topic]', or 'launch campaign'.",
      parameters: {
        type: "object",
        properties: {
          name: { type: "string", description: "Campaign name" },
          idea: { type: "string", description: "Campaign idea or topic description" },
          goal: { type: "string", enum: ["awareness", "conversion", "engagement", "education"], description: "Campaign goal" },
          target_audience: { type: "string", description: "Target audience description" },
          timeline: { type: "string", enum: ["1-week", "2-week", "4-week", "ongoing"], description: "Campaign timeline" },
          solution_id: { type: "string", description: "UUID of solution to promote (optional)" }
        },
        required: ["name", "idea"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "schedule_social_from_repurpose",
      description: "Save and schedule social media posts that were generated by repurpose_for_social. Use when user says 'schedule these social posts', 'post these to social', 'save the social posts', 'schedule them'.",
      parameters: {
        type: "object",
        properties: {
          posts: {
            type: "array",
            items: {
              type: "object",
              properties: {
                platform: { type: "string", enum: ["twitter", "linkedin", "facebook", "instagram"] },
                text: { type: "string", description: "Post content" },
                hashtags: { type: "array", items: { type: "string" } }
              },
              required: ["platform", "text"]
            },
            description: "Array of social posts to schedule"
          },
          scheduled_at: { type: "string", description: "ISO datetime to schedule posts. Null = post immediately." },
          source_content_id: { type: "string", description: "UUID of the source content item (optional)" }
        },
        required: ["posts"]
      }
    }
  }
];

export const CROSS_MODULE_TOOL_NAMES = [
  'promote_content_to_campaign', 'content_to_email',
  'campaign_content_to_engage', 'repurpose_for_social',
  'publish_to_website', 'schedule_social_from_repurpose'
];

async function getUserWorkspaceId(supabase: any, userId: string): Promise<string | null> {
  const { data } = await supabase.from('team_members')
    .select('workspace_id')
    .eq('user_id', userId)
    .limit(1).single();
  return data?.workspace_id || null;
}

export async function executeCrossModuleTool(
  toolName: string, toolArgs: any, supabase: any, userId: string
): Promise<any> {
  console.log(`[CROSS-MODULE] ${toolName} | user: ${userId}`);

  try {
    switch (toolName) {
      case 'promote_content_to_campaign': {
        // Get content item
        const { data: content, error: contentError } = await supabase.from('content_items')
          .select('id, title, content, content_type, main_keyword, solution_id')
          .eq('id', toolArgs.content_id)
          .eq('user_id', userId)
          .single();

        if (contentError || !content) {
          return { success: false, message: 'Content not found or access denied' };
        }

        // Create campaign
        const { data: campaign, error: campaignError } = await supabase.from('campaigns').insert({
          user_id: userId,
          name: toolArgs.campaign_name || `Campaign: ${content.title}`,
          original_idea: `Promoted from content: ${content.title}`,
          objective: toolArgs.objective || `Promote "${content.title}" across channels`,
          solution_id: content.solution_id || null,
          status: 'draft'
        }).select('id, name, status, created_at').single();

        if (campaignError) throw campaignError;

        // Link content to campaign
        await supabase.from('content_items')
          .update({ campaign_id: campaign.id })
          .eq('id', content.id);

        return {
          success: true,
          message: `Created campaign "${campaign.name}" from content "${content.title}"`,
          campaign,
          contentLinked: content.id
        };
      }

      case 'content_to_email': {
        // Get content
        const { data: content, error: contentError } = await supabase.from('content_items')
          .select('id, title, content, content_type')
          .eq('id', toolArgs.content_id)
          .eq('user_id', userId)
          .single();

        if (contentError || !content) {
          return { success: false, message: 'Content not found or access denied' };
        }

        // Get workspace
        const workspaceId = await getUserWorkspaceId(supabase, userId);
        if (!workspaceId) {
          return { success: false, message: 'No Engage workspace found. Visit the Engage module first.' };
        }

        // Create email campaign
        const { data: emailCampaign, error: emailError } = await supabase.from('engage_email_campaigns').insert({
          workspace_id: workspaceId,
          name: `Email: ${content.title}`,
          subject: toolArgs.subject || content.title,
          body_html: content.content,
          segment_id: toolArgs.segment_id || null,
          from_name: toolArgs.from_name || null,
          status: 'draft'
        }).select('id, name, subject, status, created_at').single();

        if (emailError) throw emailError;

        return {
          success: true,
          message: `Created email campaign "${emailCampaign.name}" from content "${content.title}"`,
          emailCampaign,
          sourceContent: { id: content.id, title: content.title }
        };
      }

      case 'campaign_content_to_engage': {
        // Get campaign's best content
        const { data: items, error: itemsError } = await supabase.from('content_items')
          .select('id, title, content, seo_score')
          .eq('campaign_id', toolArgs.campaign_id)
          .eq('user_id', userId)
          .order('seo_score', { ascending: false })
          .limit(1);

        if (itemsError || !items?.length) {
          return { success: false, message: 'No content found for this campaign' };
        }

        const topContent = items[0];
        const workspaceId = await getUserWorkspaceId(supabase, userId);
        if (!workspaceId) {
          return { success: false, message: 'No Engage workspace found.' };
        }

        const { data: emailCampaign, error: emailError } = await supabase.from('engage_email_campaigns').insert({
          workspace_id: workspaceId,
          name: `Campaign Digest: ${topContent.title}`,
          subject: toolArgs.subject || topContent.title,
          body_html: topContent.content,
          segment_id: toolArgs.segment_id || null,
          status: 'draft'
        }).select('id, name, subject, status').single();

        if (emailError) throw emailError;

        return {
          success: true,
          message: `Created email from campaign's top content "${topContent.title}"`,
          emailCampaign,
          sourceContent: topContent
        };
      }

      case 'repurpose_for_social': {
        // Get content
        const { data: content, error: contentError } = await supabase.from('content_items')
          .select('id, title, content, main_keyword')
          .eq('id', toolArgs.content_id)
          .eq('user_id', userId)
          .single();

        if (contentError || !content) {
          return { success: false, message: 'Content not found or access denied' };
        }

        // Call ai-proxy to generate social posts
        const supabaseUrl = Deno.env.get('SUPABASE_URL');
        const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

        const { data: provider } = await supabase.from('ai_service_providers')
          .select('provider, preferred_model')
          .eq('user_id', userId)
          .eq('status', 'active')
          .order('priority', { ascending: true })
          .limit(1).single();

        if (!provider) {
          return { success: false, message: 'No AI provider configured.' };
        }

        // Truncate content for the prompt
        const contentPreview = (content.content || '').replace(/<[^>]+>/g, '').substring(0, 2000);

        const proxyResponse = await fetch(`${supabaseUrl}/functions/v1/ai-proxy`, {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${supabaseKey}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            params: {
              provider: provider.provider,
              model: provider.preferred_model || 'gpt-4',
              messages: [
                {
                  role: 'system',
                  content: `Generate social media posts for the specified platforms. Return valid JSON only: { "posts": [{ "platform": "twitter", "text": "...", "hashtags": ["..."] }] }`
                },
                {
                  role: 'user',
                  content: `Repurpose this article for ${toolArgs.platforms.join(', ')}. Title: "${content.title}". Content: ${contentPreview}`
                }
              ],
              maxTokens: 1500,
              userId
            }
          })
        });

        if (!proxyResponse.ok) {
          return { success: false, message: 'Failed to generate social posts' };
        }

        const aiResult = await proxyResponse.json();
        const rawContent = aiResult.content || aiResult.choices?.[0]?.message?.content || '';

        let posts;
        try {
          const jsonMatch = rawContent.match(/\{[\s\S]*\}/);
          posts = jsonMatch ? JSON.parse(jsonMatch[0]) : { posts: [] };
        } catch {
          posts = { posts: [], raw: rawContent };
        }

        return {
          success: true,
          message: `Generated ${posts.posts?.length || 0} social posts from "${content.title}"`,
          socialPosts: posts.posts || [],
          sourceContent: { id: content.id, title: content.title }
        };
      }

      case 'publish_to_website': {
        // 1. Fetch content item
        const { data: content, error: contentError } = await supabase.from('content_items')
          .select('id, title, content, main_keyword, meta_description, slug')
          .eq('id', toolArgs.content_id)
          .eq('user_id', userId)
          .single();

        if (contentError || !content) {
          return { success: false, message: 'Content not found or access denied' };
        }

        // 2. Check for active website connection
        const { data: connection } = await supabase.from('website_connections')
          .select('provider, site_url, site_id, is_active')
          .eq('user_id', userId)
          .eq('is_active', true)
          .limit(1)
          .single();

        if (!connection) {
          return { success: false, message: 'No active website connection found. Go to Settings > Publishing to connect WordPress or Wix.' };
        }

        // 3. Call the appropriate publish edge function
        const supabaseUrl = Deno.env.get('SUPABASE_URL');
        const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
        const functionName = connection.provider === 'wordpress' ? 'publish-wordpress' : 'publish-wix';

        const publishResponse = await fetch(`${supabaseUrl}/functions/v1/${functionName}`, {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${serviceKey}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            title: content.title,
            slug: content.slug || content.title?.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
            contentMd: content.content,
            excerpt: content.meta_description || '',
            tags: content.main_keyword ? [content.main_keyword] : [],
            status: toolArgs.status || 'publish'
          })
        });

        if (!publishResponse.ok) {
          const errText = await publishResponse.text();
          return { success: false, message: `Failed to publish to ${connection.provider}: ${errText}` };
        }

        const publishResult = await publishResponse.json();

        // 4. Update content status
        await supabase.from('content_items')
          .update({
            status: 'published',
            metadata: { published_url: publishResult.url || publishResult.link, published_provider: connection.provider, published_at: new Date().toISOString() }
          })
          .eq('id', content.id);

        return {
          success: true,
          message: `Published "${content.title}" to ${connection.provider}${publishResult.url || publishResult.link ? ` — ${publishResult.url || publishResult.link}` : ''}`,
          url: publishResult.url || publishResult.link,
          provider: connection.provider
        };
      }

      case 'schedule_social_from_repurpose': {
        const workspaceId = await getUserWorkspaceId(supabase, userId);
        if (!workspaceId) {
          return { success: false, message: 'No Engage workspace found. Visit the Engage module first.' };
        }

        const posts = toolArgs.posts || [];
        if (posts.length === 0) {
          return { success: false, message: 'No posts provided to schedule.' };
        }

        const createdPosts = [];
        for (const post of posts) {
          const hashtags = post.hashtags || [];
          const fullText = hashtags.length > 0
            ? `${post.text}\n\n${hashtags.map((h: string) => h.startsWith('#') ? h : `#${h}`).join(' ')}`
            : post.text;

          // Insert social post
          const { data: socialPost, error: postError } = await supabase.from('social_posts').insert({
            workspace_id: workspaceId,
            content: fullText,
            media_urls: [],
            scheduled_at: toolArgs.scheduled_at || null,
            status: toolArgs.scheduled_at ? 'scheduled' : 'draft',
            source_content_id: toolArgs.source_content_id || null
          }).select('id').single();

          if (postError) {
            console.error('[CROSS-MODULE] Social post insert error:', postError);
            continue;
          }

          // Insert target platform
          await supabase.from('social_post_targets').insert({
            post_id: socialPost.id,
            platform: post.platform,
            status: toolArgs.scheduled_at ? 'pending' : 'draft'
          });

          createdPosts.push({ id: socialPost.id, platform: post.platform });
        }

        return {
          success: true,
          message: `${toolArgs.scheduled_at ? 'Scheduled' : 'Saved'} ${createdPosts.length} social post(s) for ${createdPosts.map(p => p.platform).join(', ')}${toolArgs.scheduled_at ? ` at ${toolArgs.scheduled_at}` : ''}`,
          posts: createdPosts
        };
      }

      default:
        return { error: `Unknown cross-module tool: ${toolName}` };
    }
  } catch (error) {
    console.error(`[CROSS-MODULE] ${toolName} | FAILED:`, error);
    return { error: String(error) };
  }
}
