import { useState, useRef, useCallback, useEffect } from 'react';
import { EnhancedChatMessage } from '@/types/enhancedChat';
import { ContextualAction } from '@/services/aiService';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';

interface LocalVisualData {
  type: 'metrics' | 'chart' | 'table' | 'progress';
  metrics?: Array<{
    id: string;
    title: string;
    value: string | number;
    icon?: string;
    change?: {
      value: number;
      type: 'increase' | 'decrease';
      period: string;
    };
  }>;
  chart?: {
    type: 'line' | 'bar' | 'pie';
    data: any[];
    categories?: string[];
    colors?: string[];
    height?: number;
  };
  table?: {
    headers: string[];
    rows: any[][];
  };
  progress?: {
    steps: Array<{
      id: string;
      title: string;
      description: string;
      completed: boolean;
    }>;
    currentStep: number;
  };
}

export interface EnhancedStreamingChatState {
  messages: EnhancedChatMessage[];
  isConnected: boolean;
  isTyping: boolean;
  isAIThinking: boolean;
  connectionStatus: 'connecting' | 'connected' | 'disconnected' | 'error';
  currentVisualData?: LocalVisualData;
  currentActions?: ContextualAction[];
}

export const useEnhancedStreamingChat = () => {
  const [state, setState] = useState<EnhancedStreamingChatState>({
    messages: [],
    isConnected: false,
    isTyping: false,
    isAIThinking: false,
    connectionStatus: 'disconnected'
  });
  
  const currentMessageRef = useRef<EnhancedChatMessage | null>(null);
  const { user } = useAuth();
  const { toast } = useToast();

  const sendEnhancedMessage = useCallback(async (content: string, fileAnalysis?: any) => {
    if (!user) {
      toast({
        title: "Authentication required",
        description: "Please log in to use the chat",
        variant: "destructive"
      });
      return;
    }

    try {
      setState(prev => ({ ...prev, isAIThinking: true }));

      // Get user context for enhanced AI
      const [solutionsResult, analyticsResult] = await Promise.all([
        supabase.from('solutions').select('*').eq('user_id', user.id),
        supabase.from('content_analytics').select('*').eq('user_id', user.id).limit(1).single()
      ]);

      // Add user message
      const userMessage: EnhancedChatMessage = {
        id: `user-${Date.now()}`,
        role: 'user',
        content,
        timestamp: new Date()
      };

      setState(prev => ({ ...prev, messages: [...prev.messages, userMessage] }));

      // Create placeholder AI message for streaming
      const aiMessage: EnhancedChatMessage = {
        id: `ai-${Date.now()}`,
        role: 'assistant',
        content: '',
        timestamp: new Date(),
        isStreaming: true
      };

      setState(prev => ({ ...prev, messages: [...prev.messages, aiMessage] }));
      currentMessageRef.current = aiMessage;

      // Get current messages for context - use ref to avoid state dependency
      const currentMessages = state.messages;
      const contextMessages = [...currentMessages, userMessage].map(msg => ({
        role: msg.role,
        content: msg.content
      }));

      // Call enhanced AI chat with context
      const { data: aiResponse, error } = await supabase.functions.invoke('enhanced-ai-chat', {
        body: {
          messages: contextMessages,
          userId: user.id,
          conversationId: `conv-${Date.now()}`,
          context: {
            solutions: solutionsResult.data || [],
            analytics: analyticsResult.data || {},
            fileAnalysis,
            workflowContext: {}
          }
        }
      });

      if (error) throw error;

      // Update message with AI response
      const finalMessage: EnhancedChatMessage = {
        ...aiMessage,
        content: aiResponse.message || '',
        isStreaming: false,
        visualData: aiResponse.visualData,
        actions: aiResponse.actions,
        metadata: {
          reasoning: `Generated by ${aiResponse.provider} (${aiResponse.model})`,
          confidence: 0.9,
          sources: [],
          actionResults: {
            provider: aiResponse.provider,
            model: aiResponse.model,
            usage: aiResponse.usage
          }
        }
      };

      setState(prev => ({
        ...prev,
        messages: prev.messages.map(msg => 
          msg.id === aiMessage.id ? finalMessage : msg
        ),
        isAIThinking: false,
        currentVisualData: aiResponse.visualData,
        currentActions: aiResponse.actions
      }));

      currentMessageRef.current = null;

    } catch (error: any) {
      console.error('Enhanced chat error:', error);
      toast({
        title: "Chat Error",
        description: error.message || "Failed to send message",
        variant: "destructive"
      });
      
      setState(prev => ({ 
        ...prev, 
        isAIThinking: false,
        messages: prev.messages.filter(msg => msg.id !== currentMessageRef.current?.id)
      }));
      currentMessageRef.current = null;
    }
  }, [user, toast]);  // Removed state.messages from dependencies

  const analyzeFile = useCallback(async (file: File): Promise<any> => {
    try {
      const reader = new FileReader();
      
      return new Promise((resolve, reject) => {
        reader.onload = async (e) => {
          try {
            const content = e.target?.result as string;
            
            // Basic file analysis
            const analysis = {
              name: file.name,
              size: file.size,
              type: file.type,
              content: file.type.includes('text') ? content : null,
              preview: content?.substring(0, 1000) + (content?.length > 1000 ? '...' : ''),
              wordCount: file.type.includes('text') ? content.split(/\s+/).length : 0,
              insights: []
            };

            // Enhanced analysis with AI
            if (analysis.content && user) {
              const { data: aiAnalysis } = await supabase.functions.invoke('enhanced-ai-chat', {
                body: {
                  messages: [{
                    role: 'user',
                    content: `Please analyze this file content and provide key insights, summary, and actionable recommendations:\n\n${analysis.preview}`
                  }],
                  userId: user.id,
                  context: { fileAnalysis: true }
                }
              });

              if (aiAnalysis?.message) {
                analysis.insights = [aiAnalysis.message];
              }
            }

            resolve(analysis);
          } catch (error) {
            reject(error);
          }
        };

        reader.onerror = () => reject(new Error('File reading failed'));
        
        if (file.type.includes('text')) {
          reader.readAsText(file);
        } else {
          reader.readAsDataURL(file);
        }
      });
    } catch (error) {
      console.error('File analysis error:', error);
      return {
        name: file.name,
        size: file.size,
        type: file.type,
        error: 'Analysis failed'
      };
    }
  }, [user]);

  const handleAction = useCallback(async (action: ContextualAction) => {
    console.log('🔄 Handling enhanced action:', action);
    
    toast({
      title: "Action Executed",
      description: `${action.label} is being processed`,
    });
  }, [toast]);

  const clearMessages = useCallback(() => {
    setState(prev => ({ 
      ...prev, 
      messages: [],
      currentVisualData: undefined,
      currentActions: undefined
    }));
    currentMessageRef.current = null;
  }, []);

  const getPerformanceAnalytics = useCallback(async () => {
    if (!user) return null;

    try {
      const { data: analytics } = await supabase
        .from('content_analytics')
        .select('*')
        .eq('user_id', user.id)
        .single();

      return analytics;
    } catch (error) {
      console.error('Analytics fetch error:', error);
      return null;
    }
  }, [user]);

  return {
    ...state,
    sendMessage: sendEnhancedMessage,
    analyzeFile,
    handleAction,
    clearMessages,
    getPerformanceAnalytics
  };
};