
import React, { useState, useEffect } from 'react';
import { useContentBuilder } from '@/contexts/ContentBuilderContext';
import { Button } from '@/components/ui/button';
import { ContentEditor } from '@/components/content/ContentEditor';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Card, CardContent } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { toast } from 'sonner';
import { Loader2, Save, CheckCircle } from 'lucide-react';

export const ContentWritingStep = () => {
  const { state, dispatch } = useContentBuilder();
  const { mainKeyword, outline, content, additionalInstructions } = state;
  const [isGenerating, setIsGenerating] = useState(false);
  const [showOutline, setShowOutline] = useState(true);

  // Mark this step as complete when we have content
  useEffect(() => {
    if (content && content.trim().length > 100) {
      dispatch({ type: 'MARK_STEP_COMPLETED', payload: 4 });
    }
  }, [content]);

  const handleContentChange = (newContent: string) => {
    dispatch({ type: 'SET_CONTENT', payload: newContent });
  };

  const handleInstructionsChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    dispatch({ type: 'SET_ADDITIONAL_INSTRUCTIONS', payload: e.target.value });
  };

  const handleGenerateContent = async () => {
    // In a real app, this would call an AI service to generate content
    // based on the outline, keywords, and additional instructions
    
    setIsGenerating(true);
    
    try {
      // Simulate API delay
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // For demo purposes, generate a simple content based on the outline
      const generatedContent = generateDemoContent();
      
      dispatch({ type: 'SET_CONTENT', payload: generatedContent });
      toast.success('Content generated successfully');
      
    } catch (error) {
      console.error('Error generating content:', error);
      toast.error('Failed to generate content. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };
  
  const generateDemoContent = () => {
    // Simple demo content generation based on outline
    let demoContent = `# ${mainKeyword}\n\n`;
    
    outline.forEach(section => {
      demoContent += `## ${section.title}\n\n`;
      demoContent += `This is a placeholder for the ${section.title.toLowerCase()} section. In a real implementation, this would be generated by an AI writing service based on your outline and SERP analysis.\n\n`;
      
      if (section.subsections && section.subsections.length > 0) {
        section.subsections.forEach(subsection => {
          demoContent += `### ${subsection.title}\n\n`;
          demoContent += `This is a placeholder for the ${subsection.title.toLowerCase()} subsection.\n\n`;
        });
      }
    });
    
    return demoContent;
  };
  
  const handleSaveContent = () => {
    // In a real app, this would save the content to a database
    toast.success('Content saved successfully');
  };
  
  const handleToggleOutline = () => {
    setShowOutline(!showOutline);
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h3 className="text-lg font-medium">Write Your Content</h3>
          <p className="text-sm text-muted-foreground">
            Create your content based on the generated outline.
          </p>
        </div>
        
        <div className="flex gap-2">
          <Button 
            variant="outline" 
            onClick={handleToggleOutline}
          >
            {showOutline ? 'Hide Outline' : 'Show Outline'}
          </Button>
          
          <Button
            onClick={handleGenerateContent}
            disabled={isGenerating || outline.length === 0}
            className="gap-2"
          >
            {isGenerating ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                Generate Content
              </>
            )}
          </Button>
          
          <Button
            onClick={handleSaveContent}
            variant="outline"
            className="gap-2"
          >
            <Save className="h-4 w-4" />
            Save
          </Button>
        </div>
      </div>
      
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {showOutline && (
          <div className="lg:col-span-1 space-y-4">
            <Card>
              <CardContent className="pt-6">
                <h4 className="text-sm font-medium mb-4">Content Outline</h4>
                
                {outline.length > 0 ? (
                  <div className="space-y-4">
                    {outline.map((section) => (
                      <div key={section.id} className="space-y-2">
                        <div className="font-medium text-sm">{section.title}</div>
                        
                        {section.subsections && section.subsections.length > 0 && (
                          <ul className="pl-4 space-y-1">
                            {section.subsections.map((subsection) => (
                              <li key={subsection.id} className="text-sm text-muted-foreground list-disc list-inside">
                                {subsection.title}
                              </li>
                            ))}
                          </ul>
                        )}
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="text-sm text-muted-foreground">
                    No outline created yet. Go back to the previous step to create an outline.
                  </p>
                )}
              </CardContent>
            </Card>
            
            <div className="space-y-2">
              <Label htmlFor="additional-instructions">Additional Instructions</Label>
              <Textarea
                id="additional-instructions"
                placeholder="Add any specific instructions for content generation..."
                value={additionalInstructions}
                onChange={handleInstructionsChange}
                rows={4}
              />
              <p className="text-xs text-muted-foreground">
                These instructions will be used when generating content.
              </p>
            </div>
          </div>
        )}
        
        <div className={showOutline ? 'lg:col-span-2' : 'lg:col-span-3'}>
          {/* Connect to ContentEditor component */}
          <ContentEditor
            content={content}
            onContentChange={handleContentChange}
          />
        </div>
      </div>
    </div>
  );
};
