
/**
 * Action-related type definitions
 */

export type ContentBuilderActionType =
  | 'SET_CURRENT_STEP'
  | 'SET_ACTIVE_STEP'
  | 'MARK_STEP_COMPLETED'
  | 'SET_MAIN_KEYWORD'
  | 'SET_SELECTED_KEYWORDS'
  | 'ADD_SELECTED_KEYWORD'
  | 'REMOVE_SELECTED_KEYWORD'
  | 'SET_SERP_DATA'
  | 'SET_IS_ANALYZING'
  | 'SET_IS_SAVING_DATA'
  | 'SET_SERP_SELECTIONS'
  | 'ADD_SERP_SELECTION'
  | 'REMOVE_SERP_SELECTION'
  | 'TOGGLE_SERP_SELECTION'
  | 'RESET_SERP_SELECTIONS'
  | 'SET_OUTLINE'
  | 'SET_OUTLINE_SECTIONS'
  | 'SET_IS_GENERATING'
  | 'SET_CONTENT'
  | 'SET_CONTENT_TITLE'
  | 'SET_SUGGESTED_TITLES'
  | 'SET_SELECTED_CLUSTER'
  | 'SET_CONTENT_TYPE'
  | 'SET_CONTENT_FORMAT'
  | 'SET_CONTENT_INTENT'
  | 'SET_SELECTED_SOLUTION'
  | 'SELECT_SOLUTION'
  | 'SET_SEO_SCORE'
  | 'SET_SEO_IMPROVEMENTS'
  | 'SET_META_TITLE'
  | 'SET_META_DESCRIPTION'
  | 'SET_DOCUMENT_STRUCTURE'
  | 'SET_OUTLINE_AUTO_GENERATED'
  | 'SET_SOLUTION_INTEGRATION_METRICS'
  | 'SET_SELECTED_REGIONS'
  | 'SET_AVAILABLE_SOLUTIONS'
  | 'SET_CONTENT_LEAD_IN'
  | 'ADD_KEYWORD'
  | 'REMOVE_KEYWORD'
  | 'SELECT_CLUSTER';

export interface ContentBuilderAction {
  type: ContentBuilderActionType;
  payload: any;
}
